//! Stage the wasm-bindgen output into `OUT_DIR` so the native binary can embed
//! it with `include_str!`/`include_bytes!` (see `src/command/web_editor_server.rs`).
//!
//! The browser editor's wasm bundle lives in `assets/web_editor/pkg/` (gitignored,
//! generated by `wasm-bindgen`). Embedding it makes `gargo` a self-contained
//! binary, so the editor keeps working after `gargo --update` (which replaces
//! only the executable).
//!
//! When the bundle hasn't been built yet, we stage **empty** placeholders so a
//! plain `cargo build` / `cargo test` / `cargo clippy` still compiles; the server
//! detects the empty bytes at runtime and serves a "wasm not built" message.
//!
//! This script intentionally does NOT run the wasm build itself: that would
//! require `wasm-bindgen` on every native build and risk recursion. Building the
//! bundle stays an explicit step (locally and in CI) before `cargo build`.

use std::path::Path;

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let pkg = Path::new("assets/web_editor/pkg");

    for name in ["gargo_wasm.js", "gargo_wasm_bg.wasm"] {
        let src = pkg.join(name);
        let dst = Path::new(&out_dir).join(name);
        // Rebuild the embed whenever the source bundle changes (or appears).
        println!("cargo:rerun-if-changed={}", src.display());
        match std::fs::read(&src) {
            Ok(bytes) => std::fs::write(&dst, bytes)
                .unwrap_or_else(|e| panic!("staging {} into OUT_DIR: {e}", src.display())),
            // Not built yet: empty placeholder keeps the `include_*!` compiling.
            Err(_) => std::fs::write(&dst, b"")
                .unwrap_or_else(|e| panic!("writing placeholder {}: {e}", dst.display())),
        }
    }
}
